//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Test.Host {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Host.IFly")]
    public interface IFly {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFly/Fly", ReplyAction="http://tempuri.org/IFly/FlyResponse")]
        string Fly(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFly/Fly", ReplyAction="http://tempuri.org/IFly/FlyResponse")]
        System.Threading.Tasks.Task<string> FlyAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlyChannel : WCF.Test.Host.IFly, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlyClient : System.ServiceModel.ClientBase<WCF.Test.Host.IFly>, WCF.Test.Host.IFly {
        
        public FlyClient() {
        }
        
        public FlyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Fly(string name) {
            return base.Channel.Fly(name);
        }
        
        public System.Threading.Tasks.Task<string> FlyAsync(string name) {
            return base.Channel.FlyAsync(name);
        }
    }
}
